//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuianClient.ServiceAdmin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.guian.com/", ConfigurationName="ServiceAdmin.ServiceAdmin")]
    public interface ServiceAdmin {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceAdmin/LoginAdminRequest", ReplyAction="http://services.guian.com/ServiceAdmin/LoginAdminResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GuianClient.ServiceAdmin.LoginAdminResponse LoginAdmin(GuianClient.ServiceAdmin.LoginAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceAdmin/LoginAdminRequest", ReplyAction="http://services.guian.com/ServiceAdmin/LoginAdminResponse")]
        System.Threading.Tasks.Task<GuianClient.ServiceAdmin.LoginAdminResponse> LoginAdminAsync(GuianClient.ServiceAdmin.LoginAdminRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.guian.com/")]
    public partial class admin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int adminIDField;
        
        private string emailField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int adminID {
            get {
                return this.adminIDField;
            }
            set {
                this.adminIDField = value;
                this.RaisePropertyChanged("adminID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginAdmin", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class LoginAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.guian.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GuianClient.ServiceAdmin.admin arg0;
        
        public LoginAdminRequest() {
        }
        
        public LoginAdminRequest(GuianClient.ServiceAdmin.admin arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginAdminResponse", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class LoginAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.guian.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GuianClient.ServiceAdmin.admin @return;
        
        public LoginAdminResponse() {
        }
        
        public LoginAdminResponse(GuianClient.ServiceAdmin.admin @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceAdminChannel : GuianClient.ServiceAdmin.ServiceAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAdminClient : System.ServiceModel.ClientBase<GuianClient.ServiceAdmin.ServiceAdmin>, GuianClient.ServiceAdmin.ServiceAdmin {
        
        public ServiceAdminClient() {
        }
        
        public ServiceAdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuianClient.ServiceAdmin.LoginAdminResponse GuianClient.ServiceAdmin.ServiceAdmin.LoginAdmin(GuianClient.ServiceAdmin.LoginAdminRequest request) {
            return base.Channel.LoginAdmin(request);
        }
        
        public GuianClient.ServiceAdmin.admin LoginAdmin(GuianClient.ServiceAdmin.admin arg0) {
            GuianClient.ServiceAdmin.LoginAdminRequest inValue = new GuianClient.ServiceAdmin.LoginAdminRequest();
            inValue.arg0 = arg0;
            GuianClient.ServiceAdmin.LoginAdminResponse retVal = ((GuianClient.ServiceAdmin.ServiceAdmin)(this)).LoginAdmin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuianClient.ServiceAdmin.LoginAdminResponse> GuianClient.ServiceAdmin.ServiceAdmin.LoginAdminAsync(GuianClient.ServiceAdmin.LoginAdminRequest request) {
            return base.Channel.LoginAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuianClient.ServiceAdmin.LoginAdminResponse> LoginAdminAsync(GuianClient.ServiceAdmin.admin arg0) {
            GuianClient.ServiceAdmin.LoginAdminRequest inValue = new GuianClient.ServiceAdmin.LoginAdminRequest();
            inValue.arg0 = arg0;
            return ((GuianClient.ServiceAdmin.ServiceAdmin)(this)).LoginAdminAsync(inValue);
        }
    }
}
