//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuianClient.ServiceCity {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.guian.com/", ConfigurationName="ServiceCity.ServiceCity")]
    public interface ServiceCity {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceCity/getCitiesRequest", ReplyAction="http://services.guian.com/ServiceCity/getCitiesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GuianClient.ServiceCity.getCitiesResponse getCities(GuianClient.ServiceCity.getCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceCity/getCitiesRequest", ReplyAction="http://services.guian.com/ServiceCity/getCitiesResponse")]
        System.Threading.Tasks.Task<GuianClient.ServiceCity.getCitiesResponse> getCitiesAsync(GuianClient.ServiceCity.getCitiesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceCity/getCitiesByCountryRequest", ReplyAction="http://services.guian.com/ServiceCity/getCitiesByCountryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GuianClient.ServiceCity.getCitiesByCountryResponse getCitiesByCountry(GuianClient.ServiceCity.getCitiesByCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceCity/getCitiesByCountryRequest", ReplyAction="http://services.guian.com/ServiceCity/getCitiesByCountryResponse")]
        System.Threading.Tasks.Task<GuianClient.ServiceCity.getCitiesByCountryResponse> getCitiesByCountryAsync(GuianClient.ServiceCity.getCitiesByCountryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.guian.com/")]
    public partial class city : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cityIDField;
        
        private string countryField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cityID {
            get {
                return this.cityIDField;
            }
            set {
                this.cityIDField = value;
                this.RaisePropertyChanged("cityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCities", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class getCitiesRequest {
        
        public getCitiesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCitiesResponse", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class getCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.guian.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GuianClient.ServiceCity.city[] @return;
        
        public getCitiesResponse() {
        }
        
        public getCitiesResponse(GuianClient.ServiceCity.city[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCitiesByCountry", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class getCitiesByCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.guian.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getCitiesByCountryRequest() {
        }
        
        public getCitiesByCountryRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCitiesByCountryResponse", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class getCitiesByCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.guian.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GuianClient.ServiceCity.city[] @return;
        
        public getCitiesByCountryResponse() {
        }
        
        public getCitiesByCountryResponse(GuianClient.ServiceCity.city[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceCityChannel : GuianClient.ServiceCity.ServiceCity, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCityClient : System.ServiceModel.ClientBase<GuianClient.ServiceCity.ServiceCity>, GuianClient.ServiceCity.ServiceCity {
        
        public ServiceCityClient() {
        }
        
        public ServiceCityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuianClient.ServiceCity.getCitiesResponse GuianClient.ServiceCity.ServiceCity.getCities(GuianClient.ServiceCity.getCitiesRequest request) {
            return base.Channel.getCities(request);
        }
        
        public GuianClient.ServiceCity.city[] getCities() {
            GuianClient.ServiceCity.getCitiesRequest inValue = new GuianClient.ServiceCity.getCitiesRequest();
            GuianClient.ServiceCity.getCitiesResponse retVal = ((GuianClient.ServiceCity.ServiceCity)(this)).getCities(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuianClient.ServiceCity.getCitiesResponse> GuianClient.ServiceCity.ServiceCity.getCitiesAsync(GuianClient.ServiceCity.getCitiesRequest request) {
            return base.Channel.getCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuianClient.ServiceCity.getCitiesResponse> getCitiesAsync() {
            GuianClient.ServiceCity.getCitiesRequest inValue = new GuianClient.ServiceCity.getCitiesRequest();
            return ((GuianClient.ServiceCity.ServiceCity)(this)).getCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuianClient.ServiceCity.getCitiesByCountryResponse GuianClient.ServiceCity.ServiceCity.getCitiesByCountry(GuianClient.ServiceCity.getCitiesByCountryRequest request) {
            return base.Channel.getCitiesByCountry(request);
        }
        
        public GuianClient.ServiceCity.city[] getCitiesByCountry(string arg0) {
            GuianClient.ServiceCity.getCitiesByCountryRequest inValue = new GuianClient.ServiceCity.getCitiesByCountryRequest();
            inValue.arg0 = arg0;
            GuianClient.ServiceCity.getCitiesByCountryResponse retVal = ((GuianClient.ServiceCity.ServiceCity)(this)).getCitiesByCountry(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuianClient.ServiceCity.getCitiesByCountryResponse> GuianClient.ServiceCity.ServiceCity.getCitiesByCountryAsync(GuianClient.ServiceCity.getCitiesByCountryRequest request) {
            return base.Channel.getCitiesByCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuianClient.ServiceCity.getCitiesByCountryResponse> getCitiesByCountryAsync(string arg0) {
            GuianClient.ServiceCity.getCitiesByCountryRequest inValue = new GuianClient.ServiceCity.getCitiesByCountryRequest();
            inValue.arg0 = arg0;
            return ((GuianClient.ServiceCity.ServiceCity)(this)).getCitiesByCountryAsync(inValue);
        }
    }
}
