//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuianClient.ServiceEnterprise {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.guian.com/", ConfigurationName="ServiceEnterprise.ServiceEnterprise")]
    public interface ServiceEnterprise {
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceEnterprise/editEnterpriseRequest", ReplyAction="http://services.guian.com/ServiceEnterprise/editEnterpriseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuianClient.ServiceEnterprise.editEnterpriseResponse editEnterprise(GuianClient.ServiceEnterprise.editEnterpriseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceEnterprise/editEnterpriseRequest", ReplyAction="http://services.guian.com/ServiceEnterprise/editEnterpriseResponse")]
        System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.editEnterpriseResponse> editEnterpriseAsync(GuianClient.ServiceEnterprise.editEnterpriseRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceEnterprise/addEnterpriseRequest", ReplyAction="http://services.guian.com/ServiceEnterprise/addEnterpriseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuianClient.ServiceEnterprise.addEnterpriseResponse addEnterprise(GuianClient.ServiceEnterprise.addEnterpriseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceEnterprise/addEnterpriseRequest", ReplyAction="http://services.guian.com/ServiceEnterprise/addEnterpriseResponse")]
        System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.addEnterpriseResponse> addEnterpriseAsync(GuianClient.ServiceEnterprise.addEnterpriseRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceEnterprise/deleteEnterpriseRequest", ReplyAction="http://services.guian.com/ServiceEnterprise/deleteEnterpriseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GuianClient.ServiceEnterprise.deleteEnterpriseResponse deleteEnterprise(GuianClient.ServiceEnterprise.deleteEnterpriseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceEnterprise/deleteEnterpriseRequest", ReplyAction="http://services.guian.com/ServiceEnterprise/deleteEnterpriseResponse")]
        System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.deleteEnterpriseResponse> deleteEnterpriseAsync(GuianClient.ServiceEnterprise.deleteEnterpriseRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceEnterprise/getEnterprisesRequest", ReplyAction="http://services.guian.com/ServiceEnterprise/getEnterprisesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GuianClient.ServiceEnterprise.getEnterprisesResponse getEnterprises(GuianClient.ServiceEnterprise.getEnterprisesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceEnterprise/getEnterprisesRequest", ReplyAction="http://services.guian.com/ServiceEnterprise/getEnterprisesResponse")]
        System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.getEnterprisesResponse> getEnterprisesAsync(GuianClient.ServiceEnterprise.getEnterprisesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceEnterprise/LoginEnterpriseRequest", ReplyAction="http://services.guian.com/ServiceEnterprise/LoginEnterpriseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GuianClient.ServiceEnterprise.LoginEnterpriseResponse LoginEnterprise(GuianClient.ServiceEnterprise.LoginEnterpriseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceEnterprise/LoginEnterpriseRequest", ReplyAction="http://services.guian.com/ServiceEnterprise/LoginEnterpriseResponse")]
        System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.LoginEnterpriseResponse> LoginEnterpriseAsync(GuianClient.ServiceEnterprise.LoginEnterpriseRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceEnterprise/getEnterpriseByIDRequest", ReplyAction="http://services.guian.com/ServiceEnterprise/getEnterpriseByIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GuianClient.ServiceEnterprise.getEnterpriseByIDResponse getEnterpriseByID(GuianClient.ServiceEnterprise.getEnterpriseByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceEnterprise/getEnterpriseByIDRequest", ReplyAction="http://services.guian.com/ServiceEnterprise/getEnterpriseByIDResponse")]
        System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.getEnterpriseByIDResponse> getEnterpriseByIDAsync(GuianClient.ServiceEnterprise.getEnterpriseByIDRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceEnterprise/getEnterprisesByStatusRequest", ReplyAction="http://services.guian.com/ServiceEnterprise/getEnterprisesByStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GuianClient.ServiceEnterprise.getEnterprisesByStatusResponse getEnterprisesByStatus(GuianClient.ServiceEnterprise.getEnterprisesByStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.guian.com/ServiceEnterprise/getEnterprisesByStatusRequest", ReplyAction="http://services.guian.com/ServiceEnterprise/getEnterprisesByStatusResponse")]
        System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.getEnterprisesByStatusResponse> getEnterprisesByStatusAsync(GuianClient.ServiceEnterprise.getEnterprisesByStatusRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.guian.com/")]
    public partial class enterprise : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string categoryField;
        
        private string emailField;
        
        private int enterpriseIDField;
        
        private string nameField;
        
        private string passwordField;
        
        private int rUCField;
        
        private string statusField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int enterpriseID {
            get {
                return this.enterpriseIDField;
            }
            set {
                this.enterpriseIDField = value;
                this.RaisePropertyChanged("enterpriseID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int RUC {
            get {
                return this.rUCField;
            }
            set {
                this.rUCField = value;
                this.RaisePropertyChanged("RUC");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editEnterprise", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class editEnterpriseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.guian.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GuianClient.ServiceEnterprise.enterprise arg0;
        
        public editEnterpriseRequest() {
        }
        
        public editEnterpriseRequest(GuianClient.ServiceEnterprise.enterprise arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editEnterpriseResponse", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class editEnterpriseResponse {
        
        public editEnterpriseResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addEnterprise", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class addEnterpriseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.guian.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GuianClient.ServiceEnterprise.enterprise arg0;
        
        public addEnterpriseRequest() {
        }
        
        public addEnterpriseRequest(GuianClient.ServiceEnterprise.enterprise arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addEnterpriseResponse", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class addEnterpriseResponse {
        
        public addEnterpriseResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteEnterprise", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class deleteEnterpriseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.guian.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GuianClient.ServiceEnterprise.enterprise arg0;
        
        public deleteEnterpriseRequest() {
        }
        
        public deleteEnterpriseRequest(GuianClient.ServiceEnterprise.enterprise arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteEnterpriseResponse", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class deleteEnterpriseResponse {
        
        public deleteEnterpriseResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEnterprises", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class getEnterprisesRequest {
        
        public getEnterprisesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEnterprisesResponse", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class getEnterprisesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.guian.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GuianClient.ServiceEnterprise.enterprise[] @return;
        
        public getEnterprisesResponse() {
        }
        
        public getEnterprisesResponse(GuianClient.ServiceEnterprise.enterprise[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginEnterprise", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class LoginEnterpriseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.guian.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GuianClient.ServiceEnterprise.enterprise arg0;
        
        public LoginEnterpriseRequest() {
        }
        
        public LoginEnterpriseRequest(GuianClient.ServiceEnterprise.enterprise arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginEnterpriseResponse", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class LoginEnterpriseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.guian.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GuianClient.ServiceEnterprise.enterprise @return;
        
        public LoginEnterpriseResponse() {
        }
        
        public LoginEnterpriseResponse(GuianClient.ServiceEnterprise.enterprise @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEnterpriseByID", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class getEnterpriseByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.guian.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getEnterpriseByIDRequest() {
        }
        
        public getEnterpriseByIDRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEnterpriseByIDResponse", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class getEnterpriseByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.guian.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GuianClient.ServiceEnterprise.enterprise @return;
        
        public getEnterpriseByIDResponse() {
        }
        
        public getEnterpriseByIDResponse(GuianClient.ServiceEnterprise.enterprise @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEnterprisesByStatus", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class getEnterprisesByStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.guian.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getEnterprisesByStatusRequest() {
        }
        
        public getEnterprisesByStatusRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEnterprisesByStatusResponse", WrapperNamespace="http://services.guian.com/", IsWrapped=true)]
    public partial class getEnterprisesByStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.guian.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GuianClient.ServiceEnterprise.enterprise[] @return;
        
        public getEnterprisesByStatusResponse() {
        }
        
        public getEnterprisesByStatusResponse(GuianClient.ServiceEnterprise.enterprise[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceEnterpriseChannel : GuianClient.ServiceEnterprise.ServiceEnterprise, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEnterpriseClient : System.ServiceModel.ClientBase<GuianClient.ServiceEnterprise.ServiceEnterprise>, GuianClient.ServiceEnterprise.ServiceEnterprise {
        
        public ServiceEnterpriseClient() {
        }
        
        public ServiceEnterpriseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEnterpriseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEnterpriseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEnterpriseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuianClient.ServiceEnterprise.editEnterpriseResponse GuianClient.ServiceEnterprise.ServiceEnterprise.editEnterprise(GuianClient.ServiceEnterprise.editEnterpriseRequest request) {
            return base.Channel.editEnterprise(request);
        }
        
        public void editEnterprise(GuianClient.ServiceEnterprise.enterprise arg0) {
            GuianClient.ServiceEnterprise.editEnterpriseRequest inValue = new GuianClient.ServiceEnterprise.editEnterpriseRequest();
            inValue.arg0 = arg0;
            GuianClient.ServiceEnterprise.editEnterpriseResponse retVal = ((GuianClient.ServiceEnterprise.ServiceEnterprise)(this)).editEnterprise(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.editEnterpriseResponse> GuianClient.ServiceEnterprise.ServiceEnterprise.editEnterpriseAsync(GuianClient.ServiceEnterprise.editEnterpriseRequest request) {
            return base.Channel.editEnterpriseAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.editEnterpriseResponse> editEnterpriseAsync(GuianClient.ServiceEnterprise.enterprise arg0) {
            GuianClient.ServiceEnterprise.editEnterpriseRequest inValue = new GuianClient.ServiceEnterprise.editEnterpriseRequest();
            inValue.arg0 = arg0;
            return ((GuianClient.ServiceEnterprise.ServiceEnterprise)(this)).editEnterpriseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuianClient.ServiceEnterprise.addEnterpriseResponse GuianClient.ServiceEnterprise.ServiceEnterprise.addEnterprise(GuianClient.ServiceEnterprise.addEnterpriseRequest request) {
            return base.Channel.addEnterprise(request);
        }
        
        public void addEnterprise(GuianClient.ServiceEnterprise.enterprise arg0) {
            GuianClient.ServiceEnterprise.addEnterpriseRequest inValue = new GuianClient.ServiceEnterprise.addEnterpriseRequest();
            inValue.arg0 = arg0;
            GuianClient.ServiceEnterprise.addEnterpriseResponse retVal = ((GuianClient.ServiceEnterprise.ServiceEnterprise)(this)).addEnterprise(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.addEnterpriseResponse> GuianClient.ServiceEnterprise.ServiceEnterprise.addEnterpriseAsync(GuianClient.ServiceEnterprise.addEnterpriseRequest request) {
            return base.Channel.addEnterpriseAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.addEnterpriseResponse> addEnterpriseAsync(GuianClient.ServiceEnterprise.enterprise arg0) {
            GuianClient.ServiceEnterprise.addEnterpriseRequest inValue = new GuianClient.ServiceEnterprise.addEnterpriseRequest();
            inValue.arg0 = arg0;
            return ((GuianClient.ServiceEnterprise.ServiceEnterprise)(this)).addEnterpriseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuianClient.ServiceEnterprise.deleteEnterpriseResponse GuianClient.ServiceEnterprise.ServiceEnterprise.deleteEnterprise(GuianClient.ServiceEnterprise.deleteEnterpriseRequest request) {
            return base.Channel.deleteEnterprise(request);
        }
        
        public void deleteEnterprise(GuianClient.ServiceEnterprise.enterprise arg0) {
            GuianClient.ServiceEnterprise.deleteEnterpriseRequest inValue = new GuianClient.ServiceEnterprise.deleteEnterpriseRequest();
            inValue.arg0 = arg0;
            GuianClient.ServiceEnterprise.deleteEnterpriseResponse retVal = ((GuianClient.ServiceEnterprise.ServiceEnterprise)(this)).deleteEnterprise(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.deleteEnterpriseResponse> GuianClient.ServiceEnterprise.ServiceEnterprise.deleteEnterpriseAsync(GuianClient.ServiceEnterprise.deleteEnterpriseRequest request) {
            return base.Channel.deleteEnterpriseAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.deleteEnterpriseResponse> deleteEnterpriseAsync(GuianClient.ServiceEnterprise.enterprise arg0) {
            GuianClient.ServiceEnterprise.deleteEnterpriseRequest inValue = new GuianClient.ServiceEnterprise.deleteEnterpriseRequest();
            inValue.arg0 = arg0;
            return ((GuianClient.ServiceEnterprise.ServiceEnterprise)(this)).deleteEnterpriseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuianClient.ServiceEnterprise.getEnterprisesResponse GuianClient.ServiceEnterprise.ServiceEnterprise.getEnterprises(GuianClient.ServiceEnterprise.getEnterprisesRequest request) {
            return base.Channel.getEnterprises(request);
        }
        
        public GuianClient.ServiceEnterprise.enterprise[] getEnterprises() {
            GuianClient.ServiceEnterprise.getEnterprisesRequest inValue = new GuianClient.ServiceEnterprise.getEnterprisesRequest();
            GuianClient.ServiceEnterprise.getEnterprisesResponse retVal = ((GuianClient.ServiceEnterprise.ServiceEnterprise)(this)).getEnterprises(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.getEnterprisesResponse> GuianClient.ServiceEnterprise.ServiceEnterprise.getEnterprisesAsync(GuianClient.ServiceEnterprise.getEnterprisesRequest request) {
            return base.Channel.getEnterprisesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.getEnterprisesResponse> getEnterprisesAsync() {
            GuianClient.ServiceEnterprise.getEnterprisesRequest inValue = new GuianClient.ServiceEnterprise.getEnterprisesRequest();
            return ((GuianClient.ServiceEnterprise.ServiceEnterprise)(this)).getEnterprisesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuianClient.ServiceEnterprise.LoginEnterpriseResponse GuianClient.ServiceEnterprise.ServiceEnterprise.LoginEnterprise(GuianClient.ServiceEnterprise.LoginEnterpriseRequest request) {
            return base.Channel.LoginEnterprise(request);
        }
        
        public GuianClient.ServiceEnterprise.enterprise LoginEnterprise(GuianClient.ServiceEnterprise.enterprise arg0) {
            GuianClient.ServiceEnterprise.LoginEnterpriseRequest inValue = new GuianClient.ServiceEnterprise.LoginEnterpriseRequest();
            inValue.arg0 = arg0;
            GuianClient.ServiceEnterprise.LoginEnterpriseResponse retVal = ((GuianClient.ServiceEnterprise.ServiceEnterprise)(this)).LoginEnterprise(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.LoginEnterpriseResponse> GuianClient.ServiceEnterprise.ServiceEnterprise.LoginEnterpriseAsync(GuianClient.ServiceEnterprise.LoginEnterpriseRequest request) {
            return base.Channel.LoginEnterpriseAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.LoginEnterpriseResponse> LoginEnterpriseAsync(GuianClient.ServiceEnterprise.enterprise arg0) {
            GuianClient.ServiceEnterprise.LoginEnterpriseRequest inValue = new GuianClient.ServiceEnterprise.LoginEnterpriseRequest();
            inValue.arg0 = arg0;
            return ((GuianClient.ServiceEnterprise.ServiceEnterprise)(this)).LoginEnterpriseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuianClient.ServiceEnterprise.getEnterpriseByIDResponse GuianClient.ServiceEnterprise.ServiceEnterprise.getEnterpriseByID(GuianClient.ServiceEnterprise.getEnterpriseByIDRequest request) {
            return base.Channel.getEnterpriseByID(request);
        }
        
        public GuianClient.ServiceEnterprise.enterprise getEnterpriseByID(int arg0) {
            GuianClient.ServiceEnterprise.getEnterpriseByIDRequest inValue = new GuianClient.ServiceEnterprise.getEnterpriseByIDRequest();
            inValue.arg0 = arg0;
            GuianClient.ServiceEnterprise.getEnterpriseByIDResponse retVal = ((GuianClient.ServiceEnterprise.ServiceEnterprise)(this)).getEnterpriseByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.getEnterpriseByIDResponse> GuianClient.ServiceEnterprise.ServiceEnterprise.getEnterpriseByIDAsync(GuianClient.ServiceEnterprise.getEnterpriseByIDRequest request) {
            return base.Channel.getEnterpriseByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.getEnterpriseByIDResponse> getEnterpriseByIDAsync(int arg0) {
            GuianClient.ServiceEnterprise.getEnterpriseByIDRequest inValue = new GuianClient.ServiceEnterprise.getEnterpriseByIDRequest();
            inValue.arg0 = arg0;
            return ((GuianClient.ServiceEnterprise.ServiceEnterprise)(this)).getEnterpriseByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GuianClient.ServiceEnterprise.getEnterprisesByStatusResponse GuianClient.ServiceEnterprise.ServiceEnterprise.getEnterprisesByStatus(GuianClient.ServiceEnterprise.getEnterprisesByStatusRequest request) {
            return base.Channel.getEnterprisesByStatus(request);
        }
        
        public GuianClient.ServiceEnterprise.enterprise[] getEnterprisesByStatus(string arg0) {
            GuianClient.ServiceEnterprise.getEnterprisesByStatusRequest inValue = new GuianClient.ServiceEnterprise.getEnterprisesByStatusRequest();
            inValue.arg0 = arg0;
            GuianClient.ServiceEnterprise.getEnterprisesByStatusResponse retVal = ((GuianClient.ServiceEnterprise.ServiceEnterprise)(this)).getEnterprisesByStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.getEnterprisesByStatusResponse> GuianClient.ServiceEnterprise.ServiceEnterprise.getEnterprisesByStatusAsync(GuianClient.ServiceEnterprise.getEnterprisesByStatusRequest request) {
            return base.Channel.getEnterprisesByStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<GuianClient.ServiceEnterprise.getEnterprisesByStatusResponse> getEnterprisesByStatusAsync(string arg0) {
            GuianClient.ServiceEnterprise.getEnterprisesByStatusRequest inValue = new GuianClient.ServiceEnterprise.getEnterprisesByStatusRequest();
            inValue.arg0 = arg0;
            return ((GuianClient.ServiceEnterprise.ServiceEnterprise)(this)).getEnterprisesByStatusAsync(inValue);
        }
    }
}
